results
0 { login: 'dret',
  id: 1848612,
  avatar_url: 'https://avatars1.githubusercontent.com/u/1848612?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/dret',
  html_url: 'https://github.com/dret',
  followers_url: 'https://api.github.com/users/dret/followers',
  following_url: 'https://api.github.com/users/dret/following{/other_user}',
  gists_url: 'https://api.github.com/users/dret/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/dret/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/dret/subscriptions',
  organizations_url: 'https://api.github.com/users/dret/orgs',
  repos_url: 'https://api.github.com/users/dret/repos',
  events_url: 'https://api.github.com/users/dret/events{/privacy}',
  received_events_url: 'https://api.github.com/users/dret/received_events',
  type: 'User',
  site_admin: false,
  name: 'Erik Wilde',
  company: 'CA Technologies',
  blog: 'http://dret.net/netdret/',
  location: 'Zürich, Switzerland',
  email: null,
  hireable: null,
  bio: 'API Academy member at day, Service Ecosystem Gardener and Web Plumber at night.',
  public_repos: 127,
  public_gists: 4,
  followers: 66,
  following: 10,
  created_at: '2012-06-14T01:47:00Z',
  updated_at: '2018-03-20T20:42:46Z' }
results
0 { login: 'mamund',
  id: 38344,
  avatar_url: 'https://avatars1.githubusercontent.com/u/38344?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mamund',
  html_url: 'https://github.com/mamund',
  followers_url: 'https://api.github.com/users/mamund/followers',
  following_url: 'https://api.github.com/users/mamund/following{/other_user}',
  gists_url: 'https://api.github.com/users/mamund/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/mamund/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mamund/subscriptions',
  organizations_url: 'https://api.github.com/users/mamund/orgs',
  repos_url: 'https://api.github.com/users/mamund/repos',
  events_url: 'https://api.github.com/users/mamund/events{/privacy}',
  received_events_url: 'https://api.github.com/users/mamund/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mike Amundsen',
  company: 'amundsen.com, inc.',
  blog: 'http://amundsen.com/blog/',
  location: 'Kentucky, USA',
  email: null,
  hireable: null,
  bio: 'Working to improve the quality and usability of information on the Web.',
  public_repos: 66,
  public_gists: 102,
  followers: 248,
  following: 72,
  created_at: '2008-12-04T19:04:51Z',
  updated_at: '2018-03-19T13:47:23Z' }
1 { login: 'dret',
  id: 1848612,
  avatar_url: 'https://avatars1.githubusercontent.com/u/1848612?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/dret',
  html_url: 'https://github.com/dret',
  followers_url: 'https://api.github.com/users/dret/followers',
  following_url: 'https://api.github.com/users/dret/following{/other_user}',
  gists_url: 'https://api.github.com/users/dret/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/dret/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/dret/subscriptions',
  organizations_url: 'https://api.github.com/users/dret/orgs',
  repos_url: 'https://api.github.com/users/dret/repos',
  events_url: 'https://api.github.com/users/dret/events{/privacy}',
  received_events_url: 'https://api.github.com/users/dret/received_events',
  type: 'User',
  site_admin: false,
  name: 'Erik Wilde',
  company: 'CA Technologies',
  blog: 'http://dret.net/netdret/',
  location: 'Zürich, Switzerland',
  email: null,
  hireable: null,
  bio: 'API Academy member at day, Service Ecosystem Gardener and Web Plumber at night.',
  public_repos: 127,
  public_gists: 4,
  followers: 66,
  following: 10,
  created_at: '2012-06-14T01:47:00Z',
  updated_at: '2018-03-20T20:42:46Z' }
results
0 { login: 'mamund',
  id: 38344,
  avatar_url: 'https://avatars1.githubusercontent.com/u/38344?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mamund',
  html_url: 'https://github.com/mamund',
  followers_url: 'https://api.github.com/users/mamund/followers',
  following_url: 'https://api.github.com/users/mamund/following{/other_user}',
  gists_url: 'https://api.github.com/users/mamund/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/mamund/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mamund/subscriptions',
  organizations_url: 'https://api.github.com/users/mamund/orgs',
  repos_url: 'https://api.github.com/users/mamund/repos',
  events_url: 'https://api.github.com/users/mamund/events{/privacy}',
  received_events_url: 'https://api.github.com/users/mamund/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mike Amundsen',
  company: 'amundsen.com, inc.',
  blog: 'http://amundsen.com/blog/',
  location: 'Kentucky, USA',
  email: null,
  hireable: null,
  bio: 'Working to improve the quality and usability of information on the Web.',
  public_repos: 66,
  public_gists: 102,
  followers: 248,
  following: 72,
  created_at: '2008-12-04T19:04:51Z',
  updated_at: '2018-03-19T13:47:23Z' }
